#!/bin/bash

psql -c "CREATE USER $PG_USER WITH PASSWORD '$PG_PASSWORD'"
psql -c "CREATE DATABASE $PG_DATABASE"
psql -c "GRANT ALL PRIVILEGES ON DATABASE $PG_DATABASE TO $PG_USER"
psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $PG_USER";
psql -c "ALTER DATABASE $PG_DATABASE OWNER TO $PG_USER";
psql $PG_DATABASE -c "ALTER SCHEMA \"public\" OWNER TO $PG_USER";
psql -c "ALTER USER $PG_USER CREATEDB";
