version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./env
    expose:
      - "5432"
    ports:
      - "5431:5432"
    volumes:
      - database:/var/lib/postgresql
volumes:
  database:
