version: '3.5'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./env
    expose:
      - "5432"
    volumes:
      - database:/var/lib/postgresql
    networks:
      - postgres-network
    container_name: "postgres_10"
volumes:
  database:
networks:
  postgres-network:
    external: false
    name: postgres-network
